### ISSUE TITLE
Do you have some solution about how to focus window and show?

### ISSUE THREAD

**Issue by hq229075284** [itchio/node-asfw#1]
In windows 10,I want to show the specified window at the foreground,but it works only flashes the taskbar button,not show the specified window at the foreground.

I saw some document about SetForegroundWindow,it seem to not support this feature.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms633539(v=vs.85).aspx

whether or  not have some alternative?

Thanks

**Comment by fasterthanlime** [comment]
See the `Remarks` section of that page you just linked to:

---

The system restricts which processes can set the foreground window. A process can set the foreground window only if one of the following conditions is true:

-   The process is the foreground process.
-   The process was started by the foreground process.
-   The process received the last input event.
-   There is no foreground process.
-   The process is being debugged.
-   The foreground process is not a Modern Application or the Start Screen.
-   The foreground is not locked (see [**LockSetForegroundWindow**](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633532(v=vs.85).aspx)).
-   The foreground lock time-out has expired (see **SPI_GETFOREGROUNDLOCKTIMEOUT** in [**SystemParametersInfo**](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724947(v=vs.85).aspx)).
-   No menus are active.

An application cannot force a window to the foreground while the user is working with another window. Instead, Windows flashes the taskbar button of the window to notify the user.

A process that can set the foreground window can enable another process to set the foreground window by calling the [**AllowSetForegroundWindow**](https://msdn.microsoft.com/en-us/library/windows/desktop/ms632668(v=vs.85).aspx) function. The process specified by *dwProcessId* loses the ability to set the foreground window the next time the user generates input, unless the input is directed at that process, or the next time a process calls **AllowSetForegroundWindow**, unless that process is specified.

The foreground process can disable calls to **SetForegroundWindow** by calling the [**LockSetForegroundWindow**](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633532(v=vs.85).aspx) function.

---

Flashing the taskbar is what happens when you *don't* have permission to set the foreground window.

**Comment by hq229075284** [comment]
why i don't have permission to do this ?
Is it because the windows api not allow to do this ?
if not ,i wonder what can i do for resolve it

**Comment by hq229075284** [comment]
this is my code:
```c++
#include <windows.h>

int main() {
  HWND selected = GetForegroundWindow();
  HWND prev = GetNextWindow(selected, GW_HWNDNEXT);
  SetForegroundWindow(prev);
}
```

**Comment by hq229075284** [comment]
I compiler code to .exe, then try some test:
1、when i run these code in git-bash window,it works as i expect
2、when i run these code in power-shell window,it works as i expect
3、when  i run these code in vs-code integrated window,it works not expect

The result not accord with 
> An application cannot force a window to the foreground while the user is working with another window. Instead, Windows flashes the taskbar button of the window to notify the user.

And the foreground window which be  set will lose focus
